import React from "react"
import Helmet from 'react-helmet';
import { graphql } from 'gatsby'
import Layout from "../components/layout"
import PostLink from "../components/post-link"
import HeroHeader from "../components/heroHeader"
import GithubLink from "../components/github-link";

const IndexPage = ({
  data: {
    site,
    allMarkdownRemark: { edges },
  },
}) => {

  const repos = [
    {
    "id": 179501605,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNzk1MDE2MDU=",
    "name": "middle-east",
    "full_name": "sadra/middle-east",
    "private": false,
    "owner": {
      "login": "sadra",
      "id": 18361407,
      "node_id": "MDQ6VXNlcjE4MzYxNDA3",
      "avatar_url": "https://avatars2.githubusercontent.com/u/18361407?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sadra",
      "html_url": "https://github.com/sadra",
      "followers_url": "https://api.github.com/users/sadra/followers",
      "following_url": "https://api.github.com/users/sadra/following{/other_user}",
      "gists_url": "https://api.github.com/users/sadra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sadra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sadra/subscriptions",
      "organizations_url": "https://api.github.com/users/sadra/orgs",
      "repos_url": "https://api.github.com/users/sadra/repos",
      "events_url": "https://api.github.com/users/sadra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sadra/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/sadra/middle-east",
    "description": "Middle East is Typora RTL theme",
    "fork": false,
    "url": "https://api.github.com/repos/sadra/middle-east",
    "forks_url": "https://api.github.com/repos/sadra/middle-east/forks",
    "keys_url": "https://api.github.com/repos/sadra/middle-east/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/sadra/middle-east/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/sadra/middle-east/teams",
    "hooks_url": "https://api.github.com/repos/sadra/middle-east/hooks",
    "issue_events_url": "https://api.github.com/repos/sadra/middle-east/issues/events{/number}",
    "events_url": "https://api.github.com/repos/sadra/middle-east/events",
    "assignees_url": "https://api.github.com/repos/sadra/middle-east/assignees{/user}",
    "branches_url": "https://api.github.com/repos/sadra/middle-east/branches{/branch}",
    "tags_url": "https://api.github.com/repos/sadra/middle-east/tags",
    "blobs_url": "https://api.github.com/repos/sadra/middle-east/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/sadra/middle-east/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/sadra/middle-east/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/sadra/middle-east/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/sadra/middle-east/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/sadra/middle-east/languages",
    "stargazers_url": "https://api.github.com/repos/sadra/middle-east/stargazers",
    "contributors_url": "https://api.github.com/repos/sadra/middle-east/contributors",
    "subscribers_url": "https://api.github.com/repos/sadra/middle-east/subscribers",
    "subscription_url": "https://api.github.com/repos/sadra/middle-east/subscription",
    "commits_url": "https://api.github.com/repos/sadra/middle-east/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/sadra/middle-east/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/sadra/middle-east/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/sadra/middle-east/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/sadra/middle-east/contents/{+path}",
    "compare_url": "https://api.github.com/repos/sadra/middle-east/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/sadra/middle-east/merges",
    "archive_url": "https://api.github.com/repos/sadra/middle-east/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/sadra/middle-east/downloads",
    "issues_url": "https://api.github.com/repos/sadra/middle-east/issues{/number}",
    "pulls_url": "https://api.github.com/repos/sadra/middle-east/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/sadra/middle-east/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/sadra/middle-east/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/sadra/middle-east/labels{/name}",
    "releases_url": "https://api.github.com/repos/sadra/middle-east/releases{/id}",
    "deployments_url": "https://api.github.com/repos/sadra/middle-east/deployments",
    "created_at": "2019-04-04T13:20:35Z",
    "updated_at": "2020-11-18T13:06:11Z",
    "pushed_at": "2020-10-18T20:43:57Z",
    "git_url": "git://github.com/sadra/middle-east.git",
    "ssh_url": "git@github.com:sadra/middle-east.git",
    "clone_url": "https://github.com/sadra/middle-east.git",
    "svn_url": "https://github.com/sadra/middle-east",
    "homepage": null,
    "size": 5638,
    "stargazers_count": 83,
    "watchers_count": 83,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 13,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 4,
    "license": null,
    "forks": 13,
    "open_issues": 4,
    "watchers": 83,
    "default_branch": "master"
  },
  {
    "id": 92442568,
    "node_id": "MDEwOlJlcG9zaXRvcnk5MjQ0MjU2OA==",
    "name": "AwesomeSpinner",
    "full_name": "sadra/AwesomeSpinner",
    "private": false,
    "owner": {
      "login": "sadra",
      "id": 18361407,
      "node_id": "MDQ6VXNlcjE4MzYxNDA3",
      "avatar_url": "https://avatars2.githubusercontent.com/u/18361407?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sadra",
      "html_url": "https://github.com/sadra",
      "followers_url": "https://api.github.com/users/sadra/followers",
      "following_url": "https://api.github.com/users/sadra/following{/other_user}",
      "gists_url": "https://api.github.com/users/sadra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sadra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sadra/subscriptions",
      "organizations_url": "https://api.github.com/users/sadra/orgs",
      "repos_url": "https://api.github.com/users/sadra/repos",
      "events_url": "https://api.github.com/users/sadra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sadra/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/sadra/AwesomeSpinner",
    "description": "With Awesome Spinner you can implement a material spinner with access to define direction layout and hint text.",
    "fork": false,
    "url": "https://api.github.com/repos/sadra/AwesomeSpinner",
    "forks_url": "https://api.github.com/repos/sadra/AwesomeSpinner/forks",
    "keys_url": "https://api.github.com/repos/sadra/AwesomeSpinner/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/sadra/AwesomeSpinner/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/sadra/AwesomeSpinner/teams",
    "hooks_url": "https://api.github.com/repos/sadra/AwesomeSpinner/hooks",
    "issue_events_url": "https://api.github.com/repos/sadra/AwesomeSpinner/issues/events{/number}",
    "events_url": "https://api.github.com/repos/sadra/AwesomeSpinner/events",
    "assignees_url": "https://api.github.com/repos/sadra/AwesomeSpinner/assignees{/user}",
    "branches_url": "https://api.github.com/repos/sadra/AwesomeSpinner/branches{/branch}",
    "tags_url": "https://api.github.com/repos/sadra/AwesomeSpinner/tags",
    "blobs_url": "https://api.github.com/repos/sadra/AwesomeSpinner/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/sadra/AwesomeSpinner/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/sadra/AwesomeSpinner/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/sadra/AwesomeSpinner/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/sadra/AwesomeSpinner/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/sadra/AwesomeSpinner/languages",
    "stargazers_url": "https://api.github.com/repos/sadra/AwesomeSpinner/stargazers",
    "contributors_url": "https://api.github.com/repos/sadra/AwesomeSpinner/contributors",
    "subscribers_url": "https://api.github.com/repos/sadra/AwesomeSpinner/subscribers",
    "subscription_url": "https://api.github.com/repos/sadra/AwesomeSpinner/subscription",
    "commits_url": "https://api.github.com/repos/sadra/AwesomeSpinner/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/sadra/AwesomeSpinner/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/sadra/AwesomeSpinner/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/sadra/AwesomeSpinner/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/sadra/AwesomeSpinner/contents/{+path}",
    "compare_url": "https://api.github.com/repos/sadra/AwesomeSpinner/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/sadra/AwesomeSpinner/merges",
    "archive_url": "https://api.github.com/repos/sadra/AwesomeSpinner/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/sadra/AwesomeSpinner/downloads",
    "issues_url": "https://api.github.com/repos/sadra/AwesomeSpinner/issues{/number}",
    "pulls_url": "https://api.github.com/repos/sadra/AwesomeSpinner/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/sadra/AwesomeSpinner/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/sadra/AwesomeSpinner/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/sadra/AwesomeSpinner/labels{/name}",
    "releases_url": "https://api.github.com/repos/sadra/AwesomeSpinner/releases{/id}",
    "deployments_url": "https://api.github.com/repos/sadra/AwesomeSpinner/deployments",
    "created_at": "2017-05-25T20:39:38Z",
    "updated_at": "2020-11-25T10:42:49Z",
    "pushed_at": "2019-10-19T18:18:31Z",
    "git_url": "git://github.com/sadra/AwesomeSpinner.git",
    "ssh_url": "git@github.com:sadra/AwesomeSpinner.git",
    "clone_url": "https://github.com/sadra/AwesomeSpinner.git",
    "svn_url": "https://github.com/sadra/AwesomeSpinner",
    "homepage": "http://isapanah.com",
    "size": 695,
    "stargazers_count": 59,
    "watchers_count": 59,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 10,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 9,
    "license": {
      "key": "other",
      "name": "Other",
      "spdx_id": "NOASSERTION",
      "url": null,
      "node_id": "MDc6TGljZW5zZTA="
    },
    "forks": 10,
    "open_issues": 9,
    "watchers": 59,
    "default_branch": "master"
  },
  {
    "id": 292873586,
    "node_id": "MDEwOlJlcG9zaXRvcnkyOTI4NzM1ODY=",
    "name": "one-time-activation-code",
    "full_name": "sadra/one-time-activation-code",
    "private": false,
    "owner": {
      "login": "sadra",
      "id": 18361407,
      "node_id": "MDQ6VXNlcjE4MzYxNDA3",
      "avatar_url": "https://avatars2.githubusercontent.com/u/18361407?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sadra",
      "html_url": "https://github.com/sadra",
      "followers_url": "https://api.github.com/users/sadra/followers",
      "following_url": "https://api.github.com/users/sadra/following{/other_user}",
      "gists_url": "https://api.github.com/users/sadra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sadra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sadra/subscriptions",
      "organizations_url": "https://api.github.com/users/sadra/orgs",
      "repos_url": "https://api.github.com/users/sadra/repos",
      "events_url": "https://api.github.com/users/sadra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sadra/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/sadra/one-time-activation-code",
    "description": "One Time Password npm package",
    "fork": false,
    "url": "https://api.github.com/repos/sadra/one-time-activation-code",
    "forks_url": "https://api.github.com/repos/sadra/one-time-activation-code/forks",
    "keys_url": "https://api.github.com/repos/sadra/one-time-activation-code/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/sadra/one-time-activation-code/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/sadra/one-time-activation-code/teams",
    "hooks_url": "https://api.github.com/repos/sadra/one-time-activation-code/hooks",
    "issue_events_url": "https://api.github.com/repos/sadra/one-time-activation-code/issues/events{/number}",
    "events_url": "https://api.github.com/repos/sadra/one-time-activation-code/events",
    "assignees_url": "https://api.github.com/repos/sadra/one-time-activation-code/assignees{/user}",
    "branches_url": "https://api.github.com/repos/sadra/one-time-activation-code/branches{/branch}",
    "tags_url": "https://api.github.com/repos/sadra/one-time-activation-code/tags",
    "blobs_url": "https://api.github.com/repos/sadra/one-time-activation-code/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/sadra/one-time-activation-code/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/sadra/one-time-activation-code/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/sadra/one-time-activation-code/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/sadra/one-time-activation-code/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/sadra/one-time-activation-code/languages",
    "stargazers_url": "https://api.github.com/repos/sadra/one-time-activation-code/stargazers",
    "contributors_url": "https://api.github.com/repos/sadra/one-time-activation-code/contributors",
    "subscribers_url": "https://api.github.com/repos/sadra/one-time-activation-code/subscribers",
    "subscription_url": "https://api.github.com/repos/sadra/one-time-activation-code/subscription",
    "commits_url": "https://api.github.com/repos/sadra/one-time-activation-code/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/sadra/one-time-activation-code/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/sadra/one-time-activation-code/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/sadra/one-time-activation-code/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/sadra/one-time-activation-code/contents/{+path}",
    "compare_url": "https://api.github.com/repos/sadra/one-time-activation-code/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/sadra/one-time-activation-code/merges",
    "archive_url": "https://api.github.com/repos/sadra/one-time-activation-code/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/sadra/one-time-activation-code/downloads",
    "issues_url": "https://api.github.com/repos/sadra/one-time-activation-code/issues{/number}",
    "pulls_url": "https://api.github.com/repos/sadra/one-time-activation-code/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/sadra/one-time-activation-code/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/sadra/one-time-activation-code/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/sadra/one-time-activation-code/labels{/name}",
    "releases_url": "https://api.github.com/repos/sadra/one-time-activation-code/releases{/id}",
    "deployments_url": "https://api.github.com/repos/sadra/one-time-activation-code/deployments",
    "created_at": "2020-09-04T14:49:19Z",
    "updated_at": "2020-09-16T15:24:31Z",
    "pushed_at": "2020-09-06T19:26:35Z",
    "git_url": "git://github.com/sadra/one-time-activation-code.git",
    "ssh_url": "git@github.com:sadra/one-time-activation-code.git",
    "clone_url": "https://github.com/sadra/one-time-activation-code.git",
    "svn_url": "https://github.com/sadra/one-time-activation-code",
    "homepage": null,
    "size": 1037,
    "stargazers_count": 10,
    "watchers_count": 10,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": null,
    "forks": 1,
    "open_issues": 1,
    "watchers": 10,
    "default_branch": "master"
  },
  {
    "id": 90123609,
    "node_id": "MDEwOlJlcG9zaXRvcnk5MDEyMzYwOQ==",
    "name": "awesome-medium-editor",
    "full_name": "sadra/awesome-medium-editor",
    "private": false,
    "owner": {
      "login": "sadra",
      "id": 18361407,
      "node_id": "MDQ6VXNlcjE4MzYxNDA3",
      "avatar_url": "https://avatars2.githubusercontent.com/u/18361407?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sadra",
      "html_url": "https://github.com/sadra",
      "followers_url": "https://api.github.com/users/sadra/followers",
      "following_url": "https://api.github.com/users/sadra/following{/other_user}",
      "gists_url": "https://api.github.com/users/sadra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sadra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sadra/subscriptions",
      "organizations_url": "https://api.github.com/users/sadra/orgs",
      "repos_url": "https://api.github.com/users/sadra/repos",
      "events_url": "https://api.github.com/users/sadra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sadra/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/sadra/awesome-medium-editor",
    "description": "Medium.com WYSIWYG editor clone, with RTL support.",
    "fork": false,
    "url": "https://api.github.com/repos/sadra/awesome-medium-editor",
    "forks_url": "https://api.github.com/repos/sadra/awesome-medium-editor/forks",
    "keys_url": "https://api.github.com/repos/sadra/awesome-medium-editor/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/sadra/awesome-medium-editor/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/sadra/awesome-medium-editor/teams",
    "hooks_url": "https://api.github.com/repos/sadra/awesome-medium-editor/hooks",
    "issue_events_url": "https://api.github.com/repos/sadra/awesome-medium-editor/issues/events{/number}",
    "events_url": "https://api.github.com/repos/sadra/awesome-medium-editor/events",
    "assignees_url": "https://api.github.com/repos/sadra/awesome-medium-editor/assignees{/user}",
    "branches_url": "https://api.github.com/repos/sadra/awesome-medium-editor/branches{/branch}",
    "tags_url": "https://api.github.com/repos/sadra/awesome-medium-editor/tags",
    "blobs_url": "https://api.github.com/repos/sadra/awesome-medium-editor/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/sadra/awesome-medium-editor/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/sadra/awesome-medium-editor/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/sadra/awesome-medium-editor/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/sadra/awesome-medium-editor/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/sadra/awesome-medium-editor/languages",
    "stargazers_url": "https://api.github.com/repos/sadra/awesome-medium-editor/stargazers",
    "contributors_url": "https://api.github.com/repos/sadra/awesome-medium-editor/contributors",
    "subscribers_url": "https://api.github.com/repos/sadra/awesome-medium-editor/subscribers",
    "subscription_url": "https://api.github.com/repos/sadra/awesome-medium-editor/subscription",
    "commits_url": "https://api.github.com/repos/sadra/awesome-medium-editor/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/sadra/awesome-medium-editor/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/sadra/awesome-medium-editor/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/sadra/awesome-medium-editor/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/sadra/awesome-medium-editor/contents/{+path}",
    "compare_url": "https://api.github.com/repos/sadra/awesome-medium-editor/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/sadra/awesome-medium-editor/merges",
    "archive_url": "https://api.github.com/repos/sadra/awesome-medium-editor/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/sadra/awesome-medium-editor/downloads",
    "issues_url": "https://api.github.com/repos/sadra/awesome-medium-editor/issues{/number}",
    "pulls_url": "https://api.github.com/repos/sadra/awesome-medium-editor/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/sadra/awesome-medium-editor/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/sadra/awesome-medium-editor/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/sadra/awesome-medium-editor/labels{/name}",
    "releases_url": "https://api.github.com/repos/sadra/awesome-medium-editor/releases{/id}",
    "deployments_url": "https://api.github.com/repos/sadra/awesome-medium-editor/deployments",
    "created_at": "2017-05-03T08:00:43Z",
    "updated_at": "2020-12-20T16:35:11Z",
    "pushed_at": "2017-05-07T04:52:12Z",
    "git_url": "git://github.com/sadra/awesome-medium-editor.git",
    "ssh_url": "git@github.com:sadra/awesome-medium-editor.git",
    "clone_url": "https://github.com/sadra/awesome-medium-editor.git",
    "svn_url": "https://github.com/sadra/awesome-medium-editor",
    "homepage": "http://ame.isapanah.com",
    "size": 2492,
    "stargazers_count": 12,
    "watchers_count": 12,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "other",
      "name": "Other",
      "spdx_id": "NOASSERTION",
      "url": null,
      "node_id": "MDc6TGljZW5zZTA="
    },
    "forks": 1,
    "open_issues": 0,
    "watchers": 12,
    "default_branch": "master"
  },
  {
    "id": 98732433,
    "node_id": "MDEwOlJlcG9zaXRvcnk5ODczMjQzMw==",
    "name": "NLeveLExpandableListView",
    "full_name": "sadra/NLeveLExpandableListView",
    "private": false,
    "owner": {
      "login": "sadra",
      "id": 18361407,
      "node_id": "MDQ6VXNlcjE4MzYxNDA3",
      "avatar_url": "https://avatars2.githubusercontent.com/u/18361407?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sadra",
      "html_url": "https://github.com/sadra",
      "followers_url": "https://api.github.com/users/sadra/followers",
      "following_url": "https://api.github.com/users/sadra/following{/other_user}",
      "gists_url": "https://api.github.com/users/sadra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sadra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sadra/subscriptions",
      "organizations_url": "https://api.github.com/users/sadra/orgs",
      "repos_url": "https://api.github.com/users/sadra/repos",
      "events_url": "https://api.github.com/users/sadra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sadra/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/sadra/NLeveLExpandableListView",
    "description": "This is an Android project about N-Level Expandable ListView",
    "fork": false,
    "url": "https://api.github.com/repos/sadra/NLeveLExpandableListView",
    "forks_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/forks",
    "keys_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/teams",
    "hooks_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/hooks",
    "issue_events_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/issues/events{/number}",
    "events_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/events",
    "assignees_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/assignees{/user}",
    "branches_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/branches{/branch}",
    "tags_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/tags",
    "blobs_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/languages",
    "stargazers_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/stargazers",
    "contributors_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/contributors",
    "subscribers_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/subscribers",
    "subscription_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/subscription",
    "commits_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/contents/{+path}",
    "compare_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/merges",
    "archive_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/downloads",
    "issues_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/issues{/number}",
    "pulls_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/labels{/name}",
    "releases_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/releases{/id}",
    "deployments_url": "https://api.github.com/repos/sadra/NLeveLExpandableListView/deployments",
    "created_at": "2017-07-29T12:55:46Z",
    "updated_at": "2020-10-30T11:22:32Z",
    "pushed_at": "2017-07-29T13:18:34Z",
    "git_url": "git://github.com/sadra/NLeveLExpandableListView.git",
    "ssh_url": "git@github.com:sadra/NLeveLExpandableListView.git",
    "clone_url": "https://github.com/sadra/NLeveLExpandableListView.git",
    "svn_url": "https://github.com/sadra/NLeveLExpandableListView",
    "homepage": "",
    "size": 502,
    "stargazers_count": 6,
    "watchers_count": 6,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 5,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": null,
    "forks": 5,
    "open_issues": 2,
    "watchers": 6,
    "default_branch": "master"
  },{
    "id": 77823389,
    "node_id": "MDEwOlJlcG9zaXRvcnk3NzgyMzM4OQ==",
    "name": "Pop-Up-UIView",
    "full_name": "sadra/Pop-Up-UIView",
    "private": false,
    "owner": {
      "login": "sadra",
      "id": 18361407,
      "node_id": "MDQ6VXNlcjE4MzYxNDA3",
      "avatar_url": "https://avatars2.githubusercontent.com/u/18361407?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sadra",
      "html_url": "https://github.com/sadra",
      "followers_url": "https://api.github.com/users/sadra/followers",
      "following_url": "https://api.github.com/users/sadra/following{/other_user}",
      "gists_url": "https://api.github.com/users/sadra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sadra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sadra/subscriptions",
      "organizations_url": "https://api.github.com/users/sadra/orgs",
      "repos_url": "https://api.github.com/users/sadra/repos",
      "events_url": "https://api.github.com/users/sadra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sadra/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/sadra/Pop-Up-UIView",
    "description": "This is an example to a create Pop Up UIView in with Swift language",
    "fork": false,
    "url": "https://api.github.com/repos/sadra/Pop-Up-UIView",
    "forks_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/forks",
    "keys_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/teams",
    "hooks_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/hooks",
    "issue_events_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/issues/events{/number}",
    "events_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/events",
    "assignees_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/assignees{/user}",
    "branches_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/branches{/branch}",
    "tags_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/tags",
    "blobs_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/languages",
    "stargazers_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/stargazers",
    "contributors_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/contributors",
    "subscribers_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/subscribers",
    "subscription_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/subscription",
    "commits_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/contents/{+path}",
    "compare_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/merges",
    "archive_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/downloads",
    "issues_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/issues{/number}",
    "pulls_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/labels{/name}",
    "releases_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/releases{/id}",
    "deployments_url": "https://api.github.com/repos/sadra/Pop-Up-UIView/deployments",
    "created_at": "2017-01-02T09:38:14Z",
    "updated_at": "2020-03-25T14:47:40Z",
    "pushed_at": "2017-01-05T06:00:51Z",
    "git_url": "git://github.com/sadra/Pop-Up-UIView.git",
    "ssh_url": "git@github.com:sadra/Pop-Up-UIView.git",
    "clone_url": "https://github.com/sadra/Pop-Up-UIView.git",
    "svn_url": "https://github.com/sadra/Pop-Up-UIView",
    "homepage": null,
    "size": 488,
    "stargazers_count": 4,
    "watchers_count": 4,
    "language": "Swift",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "forks": 0,
    "open_issues": 1,
    "watchers": 4,
    "default_branch": "master"
  },

  ]

  const Posts = edges
    .filter(edge => !!edge.node.frontmatter.date) // You can filter your posts based on some criteria
    .map(edge => <PostLink key={edge.node.id} post={edge.node} />)

  const Githubs = repos
  .map(repo => <GithubLink 
    key={repo.id}
    name={repo.name}
    description={repo.description}
    stars={repo.stargazers_count}
    forks={repo.forks}
    link={repo.html_url}
  />)

  return (
    <Layout>
      <Helmet>
        <title>{site.siteMetadata.title}</title>
        <meta name="description" content={site.siteMetadata.description} />
      </Helmet>
      <HeroHeader/>
      <h2>Blog Posts &darr;</h2>
      <div className="grids">
        {Posts}
      </div>
      <br/>
      <h2>Githab Repos &darr;</h2>
      <div className="grids">
        {Githubs}
      </div>
    </Layout>
  )
}

export default IndexPage
export const pageQuery = graphql`
  query indexPageQuery {
    site {
      siteMetadata {
        title
        description
      }
    }
    allMarkdownRemark(sort: { order: DESC, fields: [frontmatter___date] }) {
      edges {
        node {
          id
          excerpt(pruneLength: 250)
          frontmatter {
            date(formatString: "MMMM DD, YYYY")
            path
            title
            thumbnail
          }
        }
      }
    }
  }
`
